#!/bin/bash
echo "who am i"
echo "$USER"
echo "path process"
pwd
echo "project name"
echo ${CI_PROJECT_ID};
#echo "create new file"

truncate -s 0 ./sonar-project.properties

echo "sonar.projectKey=org.sonarqube:$CI_PROJECT_NAME
sonar.projectName=PHP :: ${CI_PROJECT_NAME}
sonar.projectVersion=1.0

sonar.language=php
sonar.sources=./
sonar.sourceEncoding=UTF-8
" >> ./sonar-project.properties

if [ ! -d tests ] ; then
    mkdir tests
fi
